# generated by Git for Windows
#test -f ~/.profile && . ~/.profile
#test -f ~/.bashrc && . ~/.bashrc
alias bnode='babel-node --presets es2015,stage-2'
alias subl='/c/Program\ Files\ \(x86\)/Sublime Text 3/subl.exe'
alias notepad="/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe"
alias tree="cmd //c tree"
alias ahk="/c/Program\ Files\ \(x86\)/AutoHotkey/AutoHotkey.exe"

#Combines git functions to smoothly push to origin master
function gits() {
git add .
git commit -a -m "$1"
git push
}

#Changes directory to the current file
function cdf(){
cd "$(dirname "$1")"
ls
}

#Changes directory and then list files function
function cds(){
cd "$1"
ls
}

# Opens config in notepad++
function config(){
notepad "C:\Users\Kevin\.bash_profile"
notepad "C:\Users\Kevin\.bashrc"
notepad "C:\Users\Kevin\Documents\Code\Configs\Bash Settings\.bashrc"
}

# Go to the code folder
function home(){
    cds "C:\Users\Kevin\Documents\Code"
}

# Go to the documents folder
function documents(){
    cds ~/Documents
}

# Run MySQL config file for root
function mys(){
    mysql -u root -p < "$1"
}